### ISSUE TITLE
Use scoremarkers rather than findmarkers?

### ISSUE THREAD

**Issue by kieranrcampbell** [camlab-bioml/cytomarker#49]
Looks like the latest recommendation is to use `scoreMarkers()` - see https://rdrr.io/github/MarioniLab/scran/man/scoreMarkers.html. We should test if this has any qualitatively different / superior results

**Comment by matt-sd-watson** [comment]
`scoreMarkers` was ultimately found to produce panels that were not as cell-type robust as `findMarkers` for canonical markers and common tissue/cell types. While the method is generally faster than `findMarkers`, it was parked as the panels were not as desirable.
